# Your Name or Company
title: Sarah Raviola

# Description of your website. This is used for social sharing.
description:  I am a Ph.D. candidate in economics at Duke University interested urban and public economics

# A brief blurb about yourself
content: I am a Ph.D. candidate in economics at Duke University. My research lies at the intersection of urban and public economics, with an emphasis on the provision of affordable housing in the US.


# Add your social links
social:
  - platform: email
    url: mailto:sarah.raviola@duke.edu
  - platform: twitter
    url: https://twitter.com/sarahraviola
  - platform: github
    url: https://github.com/sarahraviola


# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

sass:
    sass_dir: ./assets/ccs

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
